spring:
  application:
    name: organization-query

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432}/${DB_NAME:hris}
    username: ${DB_USER:organization_service}
    password: ${DB_PASSWORD:organization_service}
    hikari:
      maximum-pool-size: 5
      max-lifetime: 1800000
      connection-timeout: 20000
      schema: organization

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: organization-consumer
      auto-offset-reset: earliest
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='${JAAS_USERNAME:jaas}'   password='${JAAS_PASSWORD:jaas}';
      bootstrap:
        servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      spring:
        json:
          trusted:
            packages: '*'
    listener:
      ack-mode: manual_immediate
      concurrency: 1

  cloud:
    discovery:
      enabled: true
    config:
      discovery:
        service-id: config-server

server:
  port: ${SERVER_PORT:0}
  error:
    include-message: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:https://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG